
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: first
  password: 123456
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails_caurse_2_development

test:
  <<: *default
  database: rails_caurse_2_test

production:
  <<: *default
  database: rails_caurse_2_production
  username: rails_caurse_2
  password: <%= ENV['RAILS_CAURSE_2_DATABASE_PASSWORD'] %>
